name: List Directory Contents

on:
  push:
    tags:
      - 'V*.*'

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: List directory contents
      run: ls -lA
    
