name: Create Release and Attach Binaries

on:
  push:
    tags:
      - 'V*.*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install PlatformIO and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Extract Board Names
      run: python extract_boards.py > boards.txt

    - id: set-matrix
      run: echo "::set-output name=matrix::$(jq -R -s -c 'split("\n")[:-1]' boards.txt)"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Extract Tag Name
      id: get_tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Build for ${{ matrix.board }}
      run: |
        pio run -e ${{ matrix.board }}
        mv .pio/build/${{ matrix.board }}/firmware.bin .pio/build/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin

    - name: List renamed .bin files
      run: ls -l .pio/build/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Auto-release for ${{ github.ref }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Attach .bin file to Release
      run: |
        file=.pio/build/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin
        echo "Uploading $file to release..."
        if ! gh release upload ${{ steps.get_tag.outputs.tag }} $file; then
          echo "Failed to upload $file"
        fi
